# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = ""  // TODO: Add bucket name
    dynamodb_table = "terraform-locks-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "" // TODO: Add region
  }
}
