name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master  


permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        cd app/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
        
        echo "Pushing image to dockerhub..."
        docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
      env:
          DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
          DOCKER_REPOSITORY: demo

    - name: Update Argo CD values.yaml with new image tag
      run: |
        IMAGE_TAG=${{ github.sha }}
        yq -i '.appValues |= sub("tag:.*", "tag: " + strenv(IMAGE_TAG))' infra/argocd/apps/app-go/config.yaml

    - name: Commit and push the updated values.yaml
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update image tag to $IMAGE_TAG"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
